Header header

# ODrive Axis 0, Last commanded speed, in rotations per second
float32 motor_vel_cmd_0

# ODrive Axis 0, Last read speed, in rotations per second
float32 motor_vel_actual_0

# ODrive Axis 0, Last read wheel position, in rotations
float32 motor_pos_actual_0

# ODrive Axis 0, motor.current_control.Iq_setpoint
float32 motor_current_actual_0

# ODrive Axis 1, Last commanded speed, in rotations per second
float32 motor_vel_cmd_1

# ODrive Axis 1, Last read speed, in rotations per second
float32 motor_vel_actual_1

# ODrive Axis 1, Last read wheel position, in rotations
float32 motor_pos_actual_1

# ODrive Axis 1, motor.current_control.Iq_setpoint
float32 motor_current_actual_1
